---
title: "Sales Report"
author: "Steven Ponce"
date: "2022-02-28"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    code_folding: show
    df_print: paged
    theme: flatly
    highlight: tango
    toc: yes
    toc_depth: 2
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,             # hide code
    message = FALSE,
    warning =  FALSE,
    out.width = '100%',       # figure size
    out.height = '500px',       # figure size
    fig.align = 'center',
    dpi = 300
    )
``` 

```{r}
# HTML = True; PDF = False
interactive <- FALSE
```

```{r libraries}
library(pacman)
p_load(tidyverse, lubridate, tidyquant, plotly)
```

```{r scripts}
source('../00_scripts/plot_sales.R')
```

```{r}
bike_orderlines_tbl <- read_rds('../00_data/bike_sales/data_wrangled/bike_orderlines.rds')
bike_orderlines_tbl
```

# Total Sales Chart {.tabset .tabset-fade .tabset-pills}

## Quarterly Sales Trend

```{r}
plot_total_sales(unit = 'quarter', interactive = interactive)
```

## Montly Sales Trend

```{r}
plot_total_sales(unit = 'month', interactive = interactive)
``` 


## Weekly Sales Trend

```{r}
plot_total_sales(unit = 'week', date_format = '%Y-%m-%d', interactive = interactive)
``` 


# Category Sales Charts {.tabset .tabset-fade .tabset-pills}

## Road {.tabset .tabset-fade}

### Quarterly
```{r, fig.height=8}
plot_categories(category_1 = 'Road', unit = 'quarter',  ncol = 1, interactive = interactive)
```

### Monthly
```{r, fig.height=8}
plot_categories(category_1 = 'Road', unit = 'month',  ncol = 1, interactive = interactive)
```

### Weekly
```{r, fig.height=8}
plot_categories(category_1 = 'Road', unit = 'month',  date_format = '%Y-%m-%d', ncol = 1, interactive = interactive)
```

## Mountain {.tabset .tabset-fade}

### Quarterly
```{r, fig.height=8}
plot_categories(category_1 = 'Mountain', unit = 'quarter',  ncol = 1, interactive = interactive)
```

### Monthly
```{r, fig.height=8}
plot_categories(category_1 = 'Mountain', unit = 'month',  ncol = 1, interactive = interactive)
```

### Weekly
```{r, fig.height=8}
plot_categories(category_1 = 'Mountain', unit = 'month',  date_format = '%Y-%m-%d', ncol = 1, interactive = interactive)
```

