---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

# Core
library(tidyverse)
library(tidyquant)

# Interactive Visualization
library(plotly)

# Database
library(odbc)
library(RSQLite)

```


```{r}
conn <- dbConnect(RSQLite::SQLite(), "../00_data/bikes_database.db")
# dbListTables(conn = conn) get db tables
bikes_tbl      <- tbl(conn, "bikes")
bikeshops_tbl  <- tbl(conn, "bikeshops")
orderlines_tbl <- tbl(conn, "orderlines")

processed_data_tbl <- orderlines_tbl %>% 
    
    # join bikeshops and bikes tbls
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id")) %>% 
    left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>% 
    
    mutate(extended_price = quantity * price) %>% 
    collect()
    

# The following operations needed to be performed outside the db
processed_data_tbl <- processed_data_tbl %>%     
    # fixing date
    mutate(order.date = ymd(order.date)) %>% 
    # separate location
    separate(location, into = c("city", "state"), sep = ", " ) %>% 
    
    select(order.date, order.id, order.line, state, quantity, price, extended_price)

# Close the db connection
dbDisconnect(conn)
``` 


Column {data-width=350 .tabset .tabset-fade}
-----------------------------------------------------------------------

### By State

```{r}

geo_plot_tbl <- processed_data_tbl %>% 
    # aggregate data by state
    group_by(state) %>% 
    summarise(total_revenue = sum(extended_price)) %>% 
    ungroup() %>% 

    # create label for tooltip
    mutate(label_text = str_glue("State: {state}
                                 Revenue: {scales::dollar(total_revenue)}"))
```



```{r}
geo_plot_tbl %>% 
    plot_geo(locationmode = "USA-states") %>%
    add_trace(z         = ~ total_revenue, 
              locations = ~ state, 
              color     = ~ total_revenue,
              text      = ~ label_text,
              colors    = ~ "Blues") %>% 
    
    # specify some map projection/options
    layout(
        geo = list(
            scope = "usa",
            projection = list(type = "albers usa"),
            showlakes  = TRUE,
            lakecolor  = toRGB("white")
        )
    )
    

```



### Chart D

```{r}

```

Page 2 {data-orientation=columns}
=======================================================================

Column {data-width=200}
-----------------------------------------------------------------------

### Chart E

```{r}

```

Column {data-width=200}
-----------------------------------------------------------------------

### Chart F

```{r}

```
