---
title: "Price Prediction App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# 1.0 Libraries ----

# App
library(flexdashboard)

# Core
library(tidyverse)
library(tidyquant)
 
# Visualization
library(plotly)

# Modeling
library(parsnip)

# Database
library(odbc)
library(RSQLite)


# 2.0 Data ----
# Read Data
con <- dbConnect(RSQLite::SQLite(), "bikes_database.db")

# con <- dbConnect(RSQLite::SQLite(), "../Data_Science_for_Business/R-Track/Course_03_Shiny_Web_App_Part_1/DS4B_102_R_Shiny_Apps_1/06_price_prediction_app_basic/bikes_database.db")

# dbListTables(con)

bikes_tbl <- tbl(con, "bikes") %>% collect()
dbDisconnect(con)

# 3.0 Scripts ----
source("../00_scripts/02_process_data.R")
source("../00_scripts/03_make_predictions.R")


# 4.0 Model ----
model_xgboost <- read_rds("../00_models/model_xgboost.rds")
```


<!-- Inputs Area-->

Column {.sidebar}
-----------------------------------------------------------------------

Space for Inputs



<!-- Plot Area -->

Column {data-width=650}
-----------------------------------------------------------------------

```{r}
new_bike_tbl <- generate_new_bike(
    bike_model     = "Jekyll Al 1 Black Inc.", 
    category_1     = "Mountain", 
    category_2     = "Over Mountain", 
    frame_material = "Aluminum", 
    .ml_model      = model_xgboost)
```


### Price Prediction vs. Product Portfolio

```{r}
bind_bike_predictions(bikes_tbl, new_bike_tbl) %>% 
    plot_bike_prediction(interactive = TRUE)
```


<!-- Table Area -->

Column {data-width=350}
-----------------------------------------------------------------------

### Price Prediction Used These Features

```{r}
new_bike_tbl %>% format_table()
```
 


